# Generated by Django 3.0.6 on 2020-05-20 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('uuid', models.IntegerField(primary_key=True, serialize=False)),
                ('last_changed', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DomainCategory',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IoTApplication',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('version', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IPRule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chain', models.CharField(max_length=6)),
                ('destination_port', models.IntegerField()),
                ('packet_type', models.CharField(max_length=10)),
                ('action', models.CharField(max_length=15)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_rule', to='rest.Device')),
            ],
            options={
                'verbose_name_plural': 'IP_Rules',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='DomainProvider',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=500)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.DomainCategory')),
            ],
        ),
        migrations.CreateModel(
            name='DomainConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.DomainCategory')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.Device')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='applications',
            field=models.ManyToManyField(blank=True, related_name='App', to='rest.IoTApplication'),
        ),
        migrations.AddField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
