# Generated by Django 3.0.6 on 2020-06-19 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domainconfig',
            name='category',
        ),
        migrations.RemoveField(
            model_name='domainconfig',
            name='device',
        ),
        migrations.RemoveField(
            model_name='domainprovider',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='device',
            name='last_changed',
        ),
        migrations.DeleteModel(
            name='DomainCategory',
        ),
        migrations.DeleteModel(
            name='DomainConfig',
        ),
        migrations.DeleteModel(
            name='DomainProvider',
        ),
    ]
